about = {
  "fullname": "RaulAlbuquerque",
  "name": "raul",
  "aboutMe": "Sou um desenvolvedor Front-End com um perfil criativo, extremamente interessado em tecnologia e pela capacidade de promover experiências através de uma tela. Fui Oficial do Exército durante 7 (sete) anos, onde pude desenvolver minha disciplina, resiliência, responsabilidade, liderança, colaboratividade, equilíbrio emocional, flexibilidade e sempre busquei solucionar os problemas da melhor forma. Nesse período, tive contato com pessoas de diferentes locais do país, fortalecendo minha empatia, comunicação e capacidade de trabalhar em equipe.",
  "hardskills": [
    "html",
    "css",
    "sass",
    "less",
    "jquery",
    "bootstrap",
    "javascript",
    "typescript",
    "grunt",
    "gulp",
    "babel",
    "vue.js",
    "react",
    "redux",
    "next",
    "git",
    "github",
    "gitflow",
    "sql",
    "tailwind.css",
    "scrum",
    "kanban",
    "figma",
  ],
  "softskills": [
    "equilíbrio emocional",
    "colaboratividade",
    "empatia",
    "flexibilidade",
    "liderança",
    "responsabilidade",
    "resiliência",
    "comunicação clara",
    "disciplina",
    "capacidade de trabalhar em equipe"
  ]
}